### PR TITLE
[FIXED] restructured the directories and URL trails 

### LINKED ISSUE #18: Restructure directories
This issue tracks the efforts to restructure the entire ISTE Website CodeBase so that all pages that are **NOT** index, have a proper trailing URL.

#### Current behavior:
Going on the `events` page for example shows this url: `https://iste.tcetmumbai.in/events.html`

#### Expected behavior:
Going on the events page should show this URL: `https://iste.tcetmumbai.in/events/`

### PR DESCRIPTION
**Pull request by rahulsingh2312**
> ## Description
Adjusted the directory structure to ensure proper organization of files.
Updated links and references across the codebase to reflect the new URL structure.
> 
> ## Fixes
> fixes #18 
> 
> ## Checklist
> * [x]  Trailing urls will now not show `.html` on any page of the website
> * [x]  edited all the `src` and `href` for the new structure of directory
> * [x] created a folder for events and a for core 
> * [x] created a folder for all events and moved all the images of them in thier respective folders  
>

>## testing 
>I have thoroughly tested these changes by creating a dummy repo and github pages 
>
>screenshots
>

image
image

### CODE REVIEW

**Comment by prathikshetty2002** [comment]
LGTM!

**Review by vish-rt — CHANGES_REQUESTED** [review]
Some conflicts need to be addressed due to a recent merge to main. Nothing too complicated other than prettifying the code.
It needs to be done before our workflow accepts your PR's changes.

**Comment by rahulsingh2312** [comment]
[solved] merge conflicts

**Review by vish-rt — CHANGES_REQUESTED** [review]
While the routes for events (page) and core (page) are fixed, there are some more routes within the events page which won't work.
image

Two ways to solve them would be:
- Creating a directory for every event and adding an `index.html` in all of them (this is practiced by Documentation Team for making blogs.
OR
- Revert the routes in `events/index.html` to it's previous state, other than the navbar.
However this only partially solves the issue and I recommend going for the first solution.

**Comment by rahulsingh2312** [comment]
> * [x] created a folder for all events and moved all the images of them in thier respective folders

**Review by vish-rt — APPROVED** [review]
Looks good to me.

**Pull request merged**
