### PR TITLE
[FIXED] Navbar's Inactivity

### LINKED ISSUE #17: Navbar button is not working
when u press on about/events its not working pink color stays on home only
Screenshot (232)

### PR DESCRIPTION
**Pull request by rizzabh**
# [Fixed] NavBar's Inactivity. It was static and never used to change according to the active page.
<hr>

# Checklist:
[ ] Used vanilla Javascript for same page sections (Home and About).

[ ] Did not use file names in Javascript to avoid further clashes which while Restructuring Directories. Hence Inevitably optimized.

<hr>

Fixed #17 

<hr>
##Before: 

Screenshot 2023-08-10 231137

Screenshot 2023-08-10 231014
<hr>

##After:
Screenshot 2023-08-10 231150
Screenshot 2023-08-10 231026

### CODE REVIEW

**Review by demonkillerr — APPROVED** [review]
LGTM

**Comment by rizzabh** [comment]
> LGTM

Thanks!

**Comment by demonkillerr** [comment]
it seems that it doesn't work on events page as intended

does work on the core page tho.. please have a look.

**Comment by rizzabh** [comment]
@demonkillerr I checked it. The code seems completely fine though. The deployed site is working completely fine on my pc.

**Pull request merged**
